# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-11-21 01:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registro_Mineria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=200)),
                ('cve', models.CharField(max_length=200)),
                ('texto', models.TextField(max_length=100000)),
            ],
        ),
    ]
