# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-11-23 04:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20181123_0416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diario',
            name='fecha',
            field=models.CharField(max_length=50),
        ),
    ]
