# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-11-23 04:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20181123_0426'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro_mineria',
            name='url',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
