# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-12-03 11:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20181203_0530'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registro_mineria',
            old_name='e_scarasup',
            new_name='datum',
        ),
        migrations.RenameField(
            model_name='registro_mineria',
            old_name='f_inscribe',
            new_name='direccion',
        ),
        migrations.RenameField(
            model_name='registro_mineria',
            old_name='f_presenta',
            new_name='editor',
        ),
        migrations.RenameField(
            model_name='registro_mineria',
            old_name='f_resoluci',
            new_name='f_inscmin',
        ),
        migrations.RenameField(
            model_name='registro_mineria',
            old_name='fojas',
            new_name='f_pubext',
        ),
        migrations.RenameField(
            model_name='registro_mineria',
            old_name='hectareas',
            new_name='fecha_sentencia1',
        ),
        migrations.RenameField(
            model_name='registro_mineria',
            old_name='lugar',
            new_name='fecha_sentencia2',
        ),
        migrations.RenameField(
            model_name='registro_mineria',
            old_name='n_scarasup',
            new_name='rol_minero',
        ),
        migrations.RenameField(
            model_name='registro_mineria',
            old_name='tipo',
            new_name='tipo_conce',
        ),
        migrations.RenameField(
            model_name='registro_mineria',
            old_name='rolped',
            new_name='vertices',
        ),
    ]
