# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-12-04 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20181203_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro_mineria',
            name='fojas',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
