# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-12-05 03:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_registro_mineria_fojas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vertice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boletin', models.CharField(blank=True, max_length=254, null=True)),
                ('f_boletin', models.CharField(blank=True, max_length=254, null=True)),
                ('concesion', models.CharField(blank=True, max_length=254, null=True)),
                ('region', models.CharField(blank=True, max_length=254, null=True)),
                ('roljuz', models.CharField(blank=True, max_length=254, null=True)),
                ('ident_lind', models.CharField(blank=True, max_length=254, null=True)),
                ('coordnorte', models.CharField(blank=True, max_length=254, null=True)),
                ('coordeste', models.CharField(blank=True, max_length=254, null=True)),
                ('registro_mineria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Registro_Mineria')),
            ],
        ),
    ]
