# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-01-16 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_vertice'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro_mineria',
            name='tipo_tramite',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
