# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-01-23 00:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_registro_mineria_tipo_tramite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registro_mineria',
            old_name='cartaigm',
            new_name='archivo',
        ),
        migrations.RenameField(
            model_name='registro_mineria',
            old_name='este',
            new_name='corte',
        ),
        migrations.RenameField(
            model_name='registro_mineria',
            old_name='estepi',
            new_name='f_prestrib',
        ),
        migrations.RenameField(
            model_name='registro_mineria',
            old_name='fecha_sentencia1',
            new_name='f_sentenc1',
        ),
        migrations.RenameField(
            model_name='registro_mineria',
            old_name='fecha_sentencia2',
            new_name='f_sentenc2',
        ),
        migrations.RenameField(
            model_name='registro_mineria',
            old_name='fechaped',
            new_name='hectareas',
        ),
        migrations.RenameField(
            model_name='registro_mineria',
            old_name='mtse',
            new_name='ind_metal',
        ),
        migrations.RenameField(
            model_name='registro_mineria',
            old_name='mtsn',
            new_name='lugar',
        ),
        migrations.RenameField(
            model_name='registro_mineria',
            old_name='mtso',
            new_name='rolminero',
        ),
        migrations.RemoveField(
            model_name='registro_mineria',
            name='mtss',
        ),
        migrations.RemoveField(
            model_name='registro_mineria',
            name='norte',
        ),
        migrations.RemoveField(
            model_name='registro_mineria',
            name='oeste',
        ),
        migrations.RemoveField(
            model_name='registro_mineria',
            name='ped_asoc',
        ),
        migrations.RemoveField(
            model_name='registro_mineria',
            name='rol_minero',
        ),
        migrations.RemoveField(
            model_name='registro_mineria',
            name='sur',
        ),
        migrations.RemoveField(
            model_name='registro_mineria',
            name='tipocoord',
        ),
    ]
