# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-02-17 22:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_registro_mineria_estepi'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro_mineria',
            name='cartaigm',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='registro_mineria',
            name='e_ocarasup',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='registro_mineria',
            name='este',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='registro_mineria',
            name='f_inscribe',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='registro_mineria',
            name='f_presenta',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='registro_mineria',
            name='f_resoluci',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='registro_mineria',
            name='fechaped',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='registro_mineria',
            name='mtse',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='registro_mineria',
            name='mtsn',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='registro_mineria',
            name='mtso',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='registro_mineria',
            name='mtss',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='registro_mineria',
            name='n_scarasup',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='registro_mineria',
            name='norte',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='registro_mineria',
            name='oeste',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='registro_mineria',
            name='ped_asoc',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='registro_mineria',
            name='rolped',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='registro_mineria',
            name='sur',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='registro_mineria',
            name='tipocoord',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
