# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-29 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20190225_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro_mineria',
            name='dates',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
