# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-11 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_registro_mineria_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro_mineria',
            name='rut_css',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
